name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Print FTP Host
      run: echo "FTP_Host:${{ secrets.FTP_HOST }}"

    - name: Test DNS Resolution
      run: |
        echo "Testing DNS resolution for ${{ secrets.FTP_HOST }}"
        nslookup ${{ secrets.FTP_HOST }} 8.8.8.8
        if [ $? -ne 0 ]; then
          echo "Retrying with Cloudflare DNS"
          nslookup ${{ secrets.FTP_HOST }} 1.1.1.1
        fi

    - name: Verify FTP Host Availability
      run: |
        echo "Pinging FTP Host ${{ secrets.FTP_HOST }}"
        ping -c 4 ${{ secrets.FTP_HOST }}
        if [ $? -ne 0 ]; then
          echo "FTP Host is not reachable"
          exit 1
        fi

    - name: Test FTP Connectivity
      run: |
        echo "Open FTP connection to ${{ secrets.FTP_HOST }}"
        sudo apt-get update && sudo apt-get install -y ftp
        ftp -inv ${{ secrets.FTP_HOST }} <<EOF
        bye
        EOF

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        server-dir: public_html/
        log-level: verbose
        dry-run: true
